### ISSUE TITLE
Error Platform not fount 0.96.3

### ISSUE THREAD

**Issue by Pirol62** [eifinger/here_travel_time#17]
## Version of the custom_component
1.21.x

## Configuration

```yaml

  - platform: here_travel_time
    app_id: "Id"
    app_code: "code"
    name: 'Yvonnes Fahrweg'
    origin: zone.home
    destination: zone.intersnack
    traffic_mode: true

```

## Describe the bug
I executed the config check against verion 0.96.3
I'm on 0.95.4
Result:
Error as described in header.

## Debug log

```text

General Errors: 
    - Platform not found: sensor.here_travel_time

```
