### ISSUE TITLE
Setup Failed 

### ISSUE THREAD

**Issue by almostserious** [eifinger/here_travel_time#18]
-->

## Version of the custom_component
1.3.3 installed via HACS in HASSIO

## Installation method (hacs / manual)
HACS
## Configuration

```yaml
for testing only "here_travel_time:" was added to configuration.yaml

```

## Describe the bug
Setup for the custom_component fails
Setup failed for here_travel_time: No setup function defined.
Issues persists even after restarting (and rebooting) several times
## Debug log

```text

Add your logs here.

```

**Comment by eifinger** [comment]
Your configuration is not valid. Have look at the README

**Comment by almostserious** [comment]
I cannot find the error... i am following the README to the point.
in my configuration.yaml i have:
```
default_config:
here_travel_time:
```

then i setup a sensor (i am using packages)
```
sensor:
  - platform: here_travel_time
    app_id: "MYAPPID"
    app_code: "MYAPPCODE"
    origin: "51.222975,9.267577"
    destination: "51.257430,9.335892"
```
Still, no change. Or is the Problem with my usage of Packages?
